# config_example.yaml
target_urls:
  - "http://testphp.vulnweb.com/"
off_limits: []

reports_dir: "sec-reports"
workspace_dir: "sec-work"

zap:
  enabled: true

afl:
  enabled: false

burp:
  enabled: false

generator:
  enabled: true

github:
  owner: "DaVitoria"
  repo: "pre_consulta"
  token: null

max_runtime_seconds: 600